apiVersion: v1
kind: Secret
metadata:
  name: mssql
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "sqledge-chart.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
stringData :
  SA_PASSWORD: {{ .Values.secret.sqlpassword | b64enc | quote }}