apiVersion: v1
kind: Service
metadata:
  name: {{ include "sqledge-chart.fullname" . }}
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "sqledge-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: sql
      protocol: TCP
      name: tcp
  selector:
    {{- include "sqledge-chart.selectorLabels" . | nindent 4 }}
