apiVersion: v1
kind: Service
metadata:
  name: {{ include "cartstatusprocessor-chart.fullname" . }}
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "cartstatusprocessor-chart.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }} 
  clusterIP: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.managementport }}
      name: management
    - port: {{ .Values.service.akkaremoteport }}
      name: akka-remote
  selector:
    {{- include "cartstatusprocessor-chart.selectorLabels" . | nindent 4 }}
