apiVersion: v1
kind: Service
metadata:
  name: {{ include "cartapi-chart.fullname" . }}
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "cartapi-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }} 
  clusterIP: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.managementport }}
      name: management
    - port: {{ .Values.service.akkaremoteport }}
      name: akka-remote
  selector:
    {{- include "cartapi-chart.selectorLabels" . | nindent 4 }}
