version: '3.4'

services:
  cartapiservice:
    image: ${DOCKER_REGISTRY-}cartservice
    build:
      context: CartAPI
      dockerfile: Dockerfile

  cartitemprocessor-1:
    image: ${DOCKER_REGISTRY-}cartitemprocessor
    build:
      context: CartItemProcessor-1
      dockerfile: Dockerfile


  cartprocessor-1:
    image: ${DOCKER_REGISTRY-}cartprocessor
    build:
      context: CartProcessor-1
      dockerfile: Dockerfile

  cartstatusprocessor:
    image: ${DOCKER_REGISTRY-}cartstatusprocessor
    build:
      context: CartStatusProcessor
      dockerfile: Dockerfile

  persistence:
    image: mcr.microsoft.com/azure-sql-edge:latest

