version: '3.4'

services:
  cartapiservice:
    image: ${DOCKER_REGISTRY-}cartservice
    build:
      context: CartAPI
      dockerfile: Dockerfile
    hostname: cartapiservice.web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CLUSTER__IP=cartapiservice.web
      - CLUSTER__PORT=4056
      - CLUSTER__SEEDS__0=akka.tcp://cartservice@cartapiservice.web:4056
      - CLUSTER__STARTUPMETHOD=SeedNodes
      - CLUSTER__READINESSPORT=11001
      - CLUSTER__PBMPORT=9110
      - CLUSTER__ISDOCKER=true
    ports:  
      - "8080:80"
      - "9445:9445"
      - "9110:9110"
    depends_on:
      - persistence

  cartitemprocessor-1:
    image: ${DOCKER_REGISTRY-}cartitemprocessor
    build:
      context: CartItemProcessor-1
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CLUSTER__PORT=4056
      - CLUSTER__SEEDS__0=akka.tcp://cartservice@cartapiservice.web:4056
      - CLUSTER__STARTUPMETHOD=SeedNodes
      - CLUSTER__READINESSPORT=11001
      - CLUSTER__PBMPORT=9110
      - CLUSTER__ISDOCKER=true
      - CONNECTIONSTRINGS__SQLSERVERLOCAL=Server=persistence,1433;Database=Akka;User Id=sa;Password=Conga@062023;
      - CONNECTIONSTRINGS__SQLSERVERSHARDING=Server=persistence,1433;Database=AkkaSharding;User Id=sa;Password=Conga@062023;
      - ISSQLPERSISTENCEENABLED=true
    depends_on:
      - cartapiservice
      - persistence

  cartprocessor-1:
    image: ${DOCKER_REGISTRY-}cartprocessor
    build:
      context: CartProcessor-1
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CLUSTER__PORT=4056
      - CLUSTER__SEEDS__0=akka.tcp://cartservice@cartapiservice.web:4056
      - CLUSTER__STARTUPMETHOD=SeedNodes
      - CLUSTER__READINESSPORT=11001
      - CLUSTER__PBMPORT=9110
      - CLUSTER__ISDOCKER=true
      - CONNECTIONSTRINGS__SQLSERVERLOCAL=Server=persistence,1433;Database=Akka;User Id=sa;Password=Conga@062023;
      - CONNECTIONSTRINGS__SQLSERVERSHARDING=Server=persistence,1433;Database=AkkaSharding;User Id=sa;Password=Conga@062023;
      - ISSQLPERSISTENCEENABLED=true
    depends_on:
      - cartapiservice
      - persistence

  cartstatusprocessor:
    image: ${DOCKER_REGISTRY-}cartstatusprocessor
    build:
      context: CartStatusProcessor
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CLUSTER__PORT=4056
      - CLUSTER__SEEDS__0=akka.tcp://cartservice@cartapiservice.web:4056
      - CLUSTER__STARTUPMETHOD=SeedNodes
      - CLUSTER__READINESSPORT=11001
      - CLUSTER__PBMPORT=9110
      - CLUSTER__ISDOCKER=true
      - CONNECTIONSTRINGS__SQLSERVERLOCAL=Server=persistence,1433;Database=Akka;User Id=sa;Password=Conga@062023;
      - CONNECTIONSTRINGS__SQLSERVERSHARDING=Server=persistence,1433;Database=AkkaSharding;User Id=sa;Password=Conga@062023;
      - ISSQLPERSISTENCEENABLED=true
    depends_on:
      - cartapiservice
      - persistence
  persistence:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Conga@062023
     - MSSQL_USER=SA
     - MSSQL_PID=Developer
    volumes:
      - mssql-azuresql-edge-data:/var/opt/mssql
    ports:
      - "1433:1433"
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ../provisioning/tempo.yaml:/etc/tempo.yaml
      - ../provisioning/tempo-data/:/tmp/tempo
    ports:
      - "14268:14268" # jaeger ingest
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
      - "9411:9411" # zipkin
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ../provisioning/otel-collector.yaml:/etc/otel-collector.yaml
      
  grafana:
    image: grafana/grafana:10.1.1
    volumes:
      - ../provisioning/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
volumes:
  mssql-azuresql-edge-data: