apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cartitem-processor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: cartitemprocessor
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource